### ISSUE TITLE
New Idea

### ISSUE THREAD

**Issue by jaswanthkar** [Ns-AnoNymouS/Auto-Forward-Bot#12]
You can add a function where the message is forwarded from a channel to user.

**Comment by Ns-AnoNymouS** [comment]
Yes you can do that by simply giving the id of the user to whom you want to forward messages. 
**Example:**
 `channel:user`

**And make sure that the user id that you had give must start the bot for bot to forward messages.**
This restriction is from telegram side so don't ask me why we need to start.

Hope you understood what to do if still have any queries contact me in telegram
